render:
  - type: web
    name: yieldwatch
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ALERT_THRESHOLD
        sync: false
        value: "3.0"
      - key: PYTHON_VERSION
        sync: false
        value: "3.10.13"
